services:

  dst_db:
    container_name: dst_db
    image: mariadb:10.10
    environment:
      - MARIADB_ROOT_PASSWORD=toor
      - MARIADB_DATABASE=music
    volumes:
      - type: bind
        source: ./backup
        target: /host-mnt
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 3s
      retries: 3
      timeout: 5s

  subset:
    image: condenser
    build:
      context: ./condenser
    container_name: subset
    environment:
      - CONDENSER_CONFIG=config.genre.json
      - DB_SRC_USER=root
      - DB_SRC_PASSWORD=toor
      - DB_SRC_HOST=src_db
      - DB_SRC_DATABASE=music
      - DB_SRC_PORT=3306
      - DB_DST_USER=root
      - DB_DST_PASSWORD=toor
      - DB_DST_HOST=dst_db
      - DB_DST_DATABASE=music
      - DB_DST_PORT=3306
    depends_on:
      src_db:
        condition: service_healthy
      dst_db:
        condition: service_healthy
