name: Subset and package
on: workflow_dispatch

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.10
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: music
        ports:
          - 3306:3306

    steps:
      - name: Check database dist repo
        uses: actions/checkout@v3
      - name: Checkout condenser repo
        uses: actions/checkout@v3
        with:
          repository: alexgQQ/condenser
          path: condenser/condenser
          ref: buffered
      - run: |
          sudo apt update -yq
          sudo apt install -yq mariadb-backup lsb-release mariadb-client mariadb-server gettext-base
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install toposort psycopg2-binary mysql-connector-python
      - run: |
          cp condenser/configs/* condenser/condenser/
          cp condenser/entrypoint.sh condenser/condenser/
          cd condenser/condenser
          ./entrypoint.sh
        env:
          DB_SRC_USER: ${{ secrets.DB_USER }}
          DB_SRC_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SRC_HOST: ${{ secrets.DB_HOST }}
          DB_SRC_DATABASE: music
          DB_SRC_PORT: 3306
          DB_DST_USER: root
          DB_DST_PASSWORD: toor
          DB_DST_HOST: 127.0.0.1
          DB_DST_DATABASE: music
          DB_DST_PORT: 3306
      - run: mysqldump --opt --user=root --password=toor --databases music | zstd -c > db-build/music.sql.zst
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: micro-db
          image_tag: latest
          dockerfile: ./db-build/Dockerfile.actions
          context: ./db-build
